### ISSUE TITLE
Squaremap not loading

### ISSUE THREAD

**Issue by IfgiU** [jpenilla/squaremap#103]
Hi!
I'm getting an error when starting my server, saying that the mod `adventure-platform-fabric` failed to load (Line 142).
It seems like this is a component of squaremap (Line 21), so I'm asking here.
Log: https://mclo.gs/jEbUvjo
(Note: Weirdly, mclogs says that automodpack is at fault, but I can't see how that would be possible considering squaremap is using/loading this component..?)
(Also Note: I more or less reposted this from the discord, I'm sorry if that's not okay)

**Comment by jpenilla** [comment]
Determined to be a mod conflict in discord https://discord.com/channels/390942438061113344/919746762028245012/1124048325235187823
