### ISSUE TITLE
HuskHomes2 and HuskTowns are not supported

### ISSUE THREAD

**Issue by 42Willow** [jpenilla/squaremap#105]
The wiki is outdated.

![image](https://github.com/jpenilla/squaremap/assets/70784752/6279671b-9537-43cb-8a38-96de5c6ae222)

Is there still a way to do it on the squaremap side? Maybe by acting as dynmap or something?

**Comment by jpenilla** [comment]
No, there's nothing to do from the squaremap side. I will update the wiki.
