### ISSUE TITLE
The command "/map fullrender" does not render the entire map.

### ISSUE THREAD

**Issue by WuQwQ** [jpenilla/squaremap#111]
as shown

**Comment by WuQwQ** [comment]
![73d05a8eac71764c04be0c72d1dfc5c1](https://github.com/jpenilla/squaremap/assets/122062865/3593a854-1a20-4ddb-ae5b-c3da33e97883)

**Comment by WuQwQ** [comment]
![a806524f77af82807c7ddded3faf708f](https://github.com/jpenilla/squaremap/assets/122062865/8b76ced5-3841-4f15-ae56-892a8e27cc14)

**Comment by WuQwQ** [comment]
I'm using an Earth map. 
However, the "/map fullrender" rendering process only renders most of the map, the rest of the map is rendered when the player runs over it.

**Comment by Roan-V** [comment]
Your world is missing some data required for squaremap to render those chunks, earthmaps are pretty notorious for this.

Whenever a player visits an area your server will automatically generate this data, hence why squaremap will only render the areas a player has visited

The easiest fix is to use a pregeneration plugin like chunky to generate this data for you without having to visit those areas ingame

**Comment by jpenilla** [comment]
See above explanation

**Comment by WuQwQ** [comment]
Understood. Thank you for your answer. ：)
