### ISSUE TITLE
render fails on old chunks

### ISSUE THREAD

**Issue by malmiteria** [jpenilla/squaremap#116]
I have a map generated in 1.16, that was updated in 1.17, then 1.19, then 1.20.

Squaremap full renders only render the map parts that we visited since 1.19 in the overworld.

Other than that, the nether and end seem to render correctly.

I assume it has to do with chunk not visited in the overworld because of the new biome / chunk generations in 1.18, which means those old chunks needs biome blending parameters. And i assume those are set only when those chunks are revisited / saved.
I guess this somehow impacts the renderer.

Hopefully it's "easy" to fix? i have no idea

**Comment by malmiteria** [comment]
for information:

some chunks i definitely know were generated around 1.16 near my base wouldn't render, so i tried flying over them in elytra, and rerendering the map, and they appear correctly now on the rendered map.

Other chunks that were generated in 1.16 or 1.17 aren't rendering.

So far in my tests, visiting those chunks always make it possible to render them.

**Comment by jpenilla** [comment]
Chunks from before the world height expansion don't count as generated until they are loaded again and upgraded. You can use a pregenerator plugin like Chunky to upgrade those chunks.

**Comment by malmiteria** [comment]
> Chunks from before the world height expansion don't count as generated until they are loaded again and upgraded. You can use a pregenerator plugin like Chunky to upgrade those chunks.

i'm not familiar with chunky, i can't seem to find a documentation explaining how to upgrade only existing chunk, only how to pre generate chunks that i haven't visited yet, am I missing something? Do you have a link / know specific commands to use?

I very much *don't* want to generate chunks i haven't visited yet, the point of using a map for me is to be able to see what terrain is unexplored as of right now

**Comment by jpenilla** [comment]
Not sure if Chunky has an only load/upgrade existing chunks option. `--forceUpgrade` also might work.
