### ISSUE TITLE
Forge Server crash on pauserender

### ISSUE THREAD

**Issue by phit** [jpenilla/squaremap#118]
running `/squaremap pauserender` in the console on a dedicated server, its fine when ran in singleplayer

squaremap 1.2.0
forge: 47.1.3
log: https://gist.github.com/phit/f076e6d061b19dd7d1a1c037c0ebc1fe

**Comment by phit** [comment]
thanks!

**Comment by asdolo** [comment]
I thought Forge wasn't supported by Squaremap. It's not in the [Supported platforms](https://github.com/jpenilla/squaremap?tab=readme-ov-file#supported-platforms) list.

**Comment by jpenilla** [comment]
This issue is from before Forge support was dropped in favor of NeoForge.
