### ISSUE TITLE
What are the block-per-pixels for each zoom level?

### ISSUE THREAD

**Issue by svioletg** [jpenilla/squaremap#138]
I'm writing a script to combine regions rendered out from squaremap into one big image, and where I have the user specify their zoom level I wanted to write in the blocks per pixel for each one, just to give some more information. 3 seems to be 1 block per pixel, 2 looks like 4 blocks per pixel, but beyond that I can't quite tell.

**Comment by jpenilla** [comment]
https://github.com/jpenilla/squaremap-stitcher
