### ISSUE TITLE
Reduce rendering distance on pre-generated maps

### ISSUE THREAD

**Issue by LinusLeonard** [jpenilla/squaremap#154]
Question: On pre-generated maps (with Chunky) with a world border, is it possible to configure Squaremap to render chunks around players but with a reduced rendering distance? I'm guessing the current default is to use server view distance, but I find rendering e.g. 10+10+1 x 10+10+1 chunks on smaller maps with a world border to be a bit too OP, as it won't take too many hours before the entire map is explored. Is it possible to achieve this given the current configration options?

If not, consider this a feature request/suggestion :) I.e. possibility to only render the chunk that players are currently standing in plus zero or more chunks in a radius (configurable), up and until server view distance.

**Comment by jpenilla** [comment]
No, this isn't currently a feature. What's described here is very similar to #97 though, besides the radius option. I'll be sure to include a radius option when I get around to implementing that.
