### ISSUE TITLE
Update checker asking for new version that's incompatible with server/Minecraft version

### ISSUE THREAD

**Issue by hamcoremusic** [jpenilla/squaremap#157]
In the logs on startup, if you're running version `1.2.2` with Minecraft 1.20.2, it prompts you to download `1.2.3`. However, this version is not compatible with Minecraft 1.20.2 but only Minecraft 1.20.4

**Comment by jpenilla** [comment]
If you plan on staying on outdated versions you can disable the update checker in the config. squaremap doesn't continue updates for old Minecraft versions, only the latest release is supported.
