### ISSUE TITLE
The unpkg cannot be accessed

### ISSUE THREAD

**Issue by INV-PLA** [jpenilla/squaremap#160]
The map cannot be used properly because it cannot be accessed

**Comment by jpenilla** [comment]
If you're behind some kind of firewall that blocks unpkg you'll need the edit the web files to use a CDN that isn't blocked or rehost the libraries yourself.

**Comment by INV-PLA** [comment]
> If you're behind some kind of firewall that blocks unpkg you'll need the edit the web files to use a CDN that isn't blocked or rehost the libraries yourself.

It resets automatically after editing

**Comment by jpenilla** [comment]
https://github.com/jpenilla/squaremap/wiki/Default-config.yml `settings.web-directory.auto-update`

**Comment by INV-PLA** [comment]
> https://github.com/jpenilla/squaremap/wiki/Default-config.yml `settings.web-directory.auto-update`

The solution is to download the file, throw it in and fill the local path, is there any problem with that?
