### ISSUE TITLE
can sb help me pls?

### ISSUE THREAD

**Issue by SirScarlet** [jpenilla/squaremap#168]
I am setuping my server DNS using cloudflare with this settings:
![Без назви-1](https://github.com/jpenilla/squaremap/assets/44670439/f7139547-1a9c-4935-8b44-131cc6a664fc)
And conection to server working with addres: play.mydomain.com, but map.mydomain.com does not work.
Mb you can help me?

**Comment by jpenilla** [comment]
The simplest setup would involve an A record and a reverse proxy, see the wiki for more info. If you have more questions feel free to ask in the discord, but the issue tracker is for tracking issues with squaremap, not support requests.
