### ISSUE TITLE
resetmap doesn't work

### ISSUE THREAD

**Issue by bdagenais2** [jpenilla/squaremap#19]
When running `/squaremap resetmap` without a world name, it provides an error asking for one.

When running `/squaremap resetmap <worldname>` WITH a world name, it provides an error saying it should be ran without any parameters.

![image](https://user-images.githubusercontent.com/77643321/148962694-e251e047-8a50-42b5-bccc-99482b9e9f91.png)

**Comment by Roan-V** [comment]
Run with "overworld" instead of <worldname>

**Comment by bdagenais2** [comment]
> Run with "overworld" instead of

I did

**Comment by Roan-V** [comment]
![image](https://user-images.githubusercontent.com/77012724/148990451-743a8aed-7d02-4f5d-b12f-9b9d96515650.png)
Interesting, it's the other way around, the resetmap command still uses the actual world name.

**Comment by bdagenais2** [comment]
Aha, I tried "world" and "minecraft:overworld". Neither of those worked. Just "overworld" works.

**Comment by jpenilla** [comment]
> ![image](https://user-images.githubusercontent.com/77012724/148990451-743a8aed-7d02-4f5d-b12f-9b9d96515650.png) Interesting, it's the other way around, the resetmap command still uses the actual world name.

This implies you're on an old build, the resetmap command was updated to use the correct keyed world argument a week or two ago

**Comment by jpenilla** [comment]
Unable to reproduce, `minecraft:overworld` and `overworld` both work for me on the latest build

**Comment by bdagenais2** [comment]
> Unable to reproduce, `minecraft:overworld` and `overworld` both work for me on the latest build

Confirmed - it was a version issue. Command works correctly on latest version of squaremap.
