### ISSUE TITLE
Add Y coordinate to player updates

### ISSUE THREAD

**Issue by thebuildcraft** [jpenilla/squaremap#199]
Hi.
I am making a fabric client mod that shows the position of players as waypoints in Xaero's maps, so players can see each other from further away in game. It does this by getting the position data from Squaremap. Unfortunately, the HTTP get-request just returns the x and z coordinates. This is not an issue for the map, as it is 2D. But for my mod it is not so good, because it means I can't display the waypoints at the correct height.

Solution / Request: Add Y coordinates to player updates

The link to the repo of my mod: https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero

**Comment by FordCorn** [comment]
+1 on this aswell, highly recommend passing the pull request!
