### ISSUE TITLE
No $SquaremapPlayerCapability for player player_name

### ISSUE THREAD

**Issue by amirinsight** [jpenilla/squaremap#201]
I'm running forge 1.19.4 on my server with squaremap and a bunch of other mods. I get this error when any player dies and tries to respawn. Full log here: https://mclo.gs/F2r1N7W

Everything else is fine with the mod. This exception only occurs when clicking respawn. Upon disabling this mod everything works fine. I've tried this with and without squaremap on my client but couldn't find the root of the issue. Is this a compatibility issue (with other mods)?

**Comment by jpenilla** [comment]
If this still happens on NeoForge 1.20.4 please open a new issue. I do not have time to support old versions.
