### ISSUE TITLE
Redirect Bukkit world names to corresponding worlds

### ISSUE THREAD

**Issue by gecko10000** [jpenilla/squaremap#202]
Towny has an integration for webmaps that generates a link for the map with the x and z coordinates. This works properly, except for the world name. Towny provides the Bukkit world name, but squaremap expects the Minecraft name. Ideally, there would be a way to redirect to the corresponding one (e.g. map/?world=world_nether becomes map/?world=minecraft_the_nether).

**Comment by jpenilla** [comment]
I think a better solution here is for the Towny integration to allow using the world key (namespace and value separately) in the link format. squaremap doesn't use Bukkit names for anything, it doesn't make sense to add it here, especially when `world:nether` is also a valid world key, for example.
