### ISSUE TITLE
Website map without loaded chunks?

### ISSUE THREAD

**Issue by KebabXL** [jpenilla/squaremap#23]
Hello, why i have black squares without any render in website after pregenerate full map?
Stock config ;/
![image](https://user-images.githubusercontent.com/42071696/151650856-53847c35-1fde-408b-8699-32104e1ac9af.png)

PS: Used chunky for pregeneration.
PS2: Version purpur 1.18.1 (build 1537)

**Comment by jpenilla** [comment]
This is more of a support question than an issue, which should be asked in discord, not on the issue tracker.

My advice for fixing this would be run chunky again to ensure all chunks are generated/upgraded, and then run a fullrender. If that doesn't work, feel free to ask for help in the discord channel as mentioned before.
