### ISSUE TITLE
add butto in web to switch world

### ISSUE THREAD

**Issue by XiaoPampo** [jpenilla/squaremap#234]
Can you add a button in the website map interface to quickly switch between the main world, hell, and destination

**Comment by dsmaugy** [comment]
You might be missing the overlay to switch between worlds. Hover your mouse to the right-side of the screen to open the overlay. It should look something like this:
![image](https://github.com/jpenilla/squaremap/assets/8429648/74a1027b-e9da-42d5-99ca-7c282aaecf79)
