### ISSUE TITLE
Terrafirmacraft "downed" death mechanic causing issues with squaremap, causes significant crashes

### ISSUE THREAD

**Issue by AryaElendril** [jpenilla/squaremap#249]
Hey there!

This issue is definitely due to cross-mod interactions, but I was curious whether or not this was something that could be easily fixed? It looks as though the downed animation that takes place whenever a person is killed in Terrafirmacraft causes SquareMap to be confused whenever the person dies afterwards. Terrafirmacraft will send a chat message saying that a player is bleeding to give other players a chance to go save them, but I believe it's calling similarly to the death message. I've attached the crash report, if it's something that might be able to be helped!

This is taking place in the TerraFirmaGreg modpack for 1.20.1 and we're currently using squaremap-forge-mc.1.20.1-1.2.0. It appears that the mod that is providing the "downed" mechanic is [PlayerRevive_FORGE_v2.0.25_mc1.20.1.](https://www.curseforge.com/minecraft/mc-mods/playerrevive)

Thank you!! Happy to answer any other questions if I missed anything.

[crashreport.txt](https://github.com/user-attachments/files/16116430/crashreport.txt)

**Comment by jpenilla** [comment]
Duplicate #244, #201

Unfortunately, I don't have time to debug or support old versions of the game and squaremap. If this happens on NeoForge 1.21 please open a new issue.
