### ISSUE TITLE
Add Support for the SkinsRestorer and PlaceholderAPI plugin

### ISSUE THREAD

**Issue by BAD7777** [jpenilla/squaremap#267]
#### Add Support for the SkinsRestorer Plugin

**Idea Description:**

I propose adding support for the SkinsRestorer plugin to the Squaremap interactive map plugin. This will allow the use of PlaceholderAPI to retrieve player skin data, rather than being limited to only {uuid} and {name} values. This enhancement will expand the customization and personalization capabilities of the player display on the map.

**Technical Details:**

1. **Integration with PlaceholderAPI:**
   - Enable the use of PlaceholderAPI in Squaremap's configuration, allowing placeholders to be specified for skin display.
   - Example configuration:

     ```yaml
     heads-url: "https://mc-heads.net/avatar/%skinsrestorer_texture_id_or_steve%.png"
     ```

2. **Data Handling:**
   - Implement logic to correctly process placeholders from PlaceholderAPI and substitute the appropriate values in the URL for fetching player skins.
   - Ensure that default values (e.g., Steve's skin) are used when placeholder data is not available.

3. **Requirements:**
   - Ensure that PlaceholderAPI is installed.
   - Ensure that SkinsRestorer is installed.

**Example Usage:**

- With Squaremap, SkinsRestorer, and PlaceholderAPI installed, server administrators will be able to configure player skin display on the map using URLs containing placeholders from PlaceholderAPI. This will allow more flexible and accurate representation of player skins, enhancing the visual experience of the map.

**Advantages:**

- **Flexibility:** Ability to use placeholders from PlaceholderAPI for displaying player skins.
- **Personalization:** Administrators can more precisely configure the map's appearance and player skin display.
- **Compatibility:** Support for existing popular plugins like SkinsRestorer and PlaceholderAPI.

**Conclusion:**

Adding support for the SkinsRestorer plugin and PlaceholderAPI in Squaremap will significantly enhance the functionality and customization flexibility of the plugin. This will enable server administrators to more accurately and personally display player skins on the interactive map, improving the overall map experience.

**Comment by jpenilla** [comment]
https://github.com/jpenilla/squaremap-addons/tree/master/addons/skins
