### ISSUE TITLE
I need help setting up reverse proxy for squaremap

### ISSUE THREAD

**Issue by averagePedestrian** [jpenilla/squaremap#273]
I'm having trouble setting up a reverse proxy for squaremap. Here are the details of my setup:

I've set the default port for squaremap to 39000 (as port 8080 is being used by another service on my VPS). Here's a snippet of the configuration file:
```
config-version: 2
settings:
    language-file: lang-en.yml
    debug-mode: false
    update-checker: true
    web-address: http://localhost:39000
    web-directory:
        path: web
        auto-update: true
    image-quality:
        compress-images:
            enabled: false
            value: 0.0
    internal-webserver:
        enabled: true
        bind: 0.0.0.0
        port: 39000
```

I'm using Swizzin on my VPS, which is a modular seedbox solution. I'm following their Nginx configuration guidelines. As per Swizzin's documentation (source: https://swizzin.ltd/applications/nginx), I've placed my custom nginx configuration in `/etc/nginx/apps/squaremap.conf`:
```
location /squaremap {
    proxy_pass http://localhost:39000; 
}
```
I can access squaremap's web interface directly at `http://129.x.x.x:39000`, but when I try to access it at `http://129.x.x.x/squaremap`, I receive a 404 error.

Am I doing anything incorrectly? Could you please provide guidance on how to correctly set up the reverse proxy for squaremap in this environment?

**Comment by jpenilla** [comment]
This is more of a general network administration question than a squaremap one. Someone on the Discord channel may be able to help, but the issue tracker is not the correct place for this kind of inquiry.
