### ISSUE TITLE
Help connecting to a Velocity server

### ISSUE THREAD

**Issue by TsengFayt** [jpenilla/squaremap#274]
I help run an SMP behind a Velocity proxy. Not sure what exactly we need to do to allow the plugin to listen and broadcast to our webserver. 

We've tried installing the plugin to both the Velocity server and the SMP server and opening the same ports, but it won't work. Is there a work around or specific setup we need to use to allow players to view the map but still forcing them to connect to the velocity server instead of directly to the SMP?

**Comment by jpenilla** [comment]
This is more of a general network administration question than a squaremap one. Someone on the Discord channel may be able to help, but the issue tracker is not the correct place for this kind of inquiry.
