### ISSUE TITLE
switching world sometimes remain worldborder/claim borders

### ISSUE THREAD

**Issue by hkkongou** [jpenilla/squaremap#29]
squaremap-paper-mc1.18.1-1.1.0-SNAPSHOT+cf6b1cc
paper-1.18.1-187

map: (YES, the port is 8123 but is not dynmap)
http://map.pecomc.ml:8123/

you can see, there are 2 vanilla world border showing in the same world, which is very bad.
many players reported this issue
F5 may or may not fix the problem for a sec, even tho it can fix , the problem will repeat again, is very annoying.

![unknown](https://user-images.githubusercontent.com/61608872/152996745-c4ed0231-1188-49c9-933f-845b2cecfd69.png)

**Comment by jpenilla** [comment]
the issue seems to occur when switching worlds before markers for the current world have finished loading; I'll look into it when I get the chance
