### ISSUE TITLE
Players can’t respawn after dying (atm9nf)

### ISSUE THREAD

**Issue by Hibanan** [jpenilla/squaremap#293]
Full log when this happens with multiple different players: https://paste2.org/7g4dvXLC

removing squaremap completely eliminated the problem.

Atm9 - no frills: version 0.1.15
Debian 12 host running graalvm ee java 17

**Comment by jpenilla** [comment]
Duplicate of #284, #249, #201. Please use the search feature to check for duplicates before opening issues.

**Comment by Hibanan** [comment]
You should probably have a warning that there are known game breaking bugs in your mods if you’re not willing to fix them. Cheers.
