### ISSUE TITLE
[FEATURE] Ability to mute/silence console messages during render

### ISSUE THREAD

**Issue by Strahilchu** [jpenilla/squaremap#3]
Another much needed feature that was absent from Pl3x.

During a full-render, the console get's spammed with progress logs, Dynmap and such have the ability to /dynmap quiet 10
Which can silence it or put it on an interval to only display progress every 10 seconds for example.

This would be great, Chunky also has this ability!

**Comment by jpenilla** [comment]
This has been implemented as `/map progresslogging toggle` and `/map progresslogging rate <seconds>`.

(also configurable through the config.yml)

**Comment by jpenilla** [comment]
https://github.com/jpenilla/squaremap/wiki/Commands-and-Permissions has been updated
