### ISSUE TITLE
Crash Direwolf 20 1.21 (Neoforge)

### ISSUE THREAD

**Issue by Appa1990** [jpenilla/squaremap#302]
Get an crash on startup the dedicated server
[28Sept.2024 14:18:26.247] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.neoForgeVersion, 21.1.61, --fml.fmlVersion, 4.0.24, --fml.mcVersion, 1.21.1, --fml.neoFormVersion, 20240808.144430, nogui]
[28Sept.2024 14:18:26.250] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: JVM identified as Eclipse Adoptium OpenJDK 64-Bit Server VM 21.0.4+7-LTS
[28Sept.2024 14:18:26.251] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 11.0.4+main.d2e20e43 starting: java version 21.0.4 by Eclipse Adoptium; OS Windows 10 arch amd64 version 10.0

> [14:18:28.380] [main/INFO] [loading.FMLServiceProvider/CORE]: Loading coremod script-engine for [apothic_enchanting]
> Exception in thread "main" java.lang.module.ResolutionException: Modules net.kyori.adventure.text.serializer.gson and spark export package net.kyori.adventure.text.serializer.gson.impl to module ars_elemental
>         at java.base/java.lang.module.Resolver.resolveFail(Unknown Source)
>         at java.base/java.lang.module.Resolver.failTwoSuppliers(Unknown Source)
>         at java.base/java.lang.module.Resolver.checkExportSuppliers(Unknown Source)
>         at java.base/java.lang.module.Resolver.finish(Unknown Source)
>         at java.base/java.lang.module.Configuration.<init>(Unknown Source)
>         at java.base/java.lang.module.Configuration.resolveAndBind(Unknown Source)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:54)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:101)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
>         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
>         at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)
>         at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)

**Comment by jpenilla** [comment]
This is a spark issue, see the PR linked above this comment.
