### ISSUE TITLE
Y-Coordinate Addition to Player Postition Updates

### ISSUE THREAD

**Issue by FordCorn** [jpenilla/squaremap#303]
Adding this would allow the developer of https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero to add support for squaremap to have Y-level functionality for the players position. I asked the developer in this issue here https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/issues/37 which shown his interest in the matter aswell.

**Comment by jpenilla** [comment]
#200
