### ISSUE TITLE
Request for Code Refactoring

### ISSUE THREAD

**Issue by a8kj7sea** [jpenilla/squaremap#311]
### Confusion in Web Project Structure

The web code appears complex and with no clear ways of doing things. The first time I explored the `util` package, it surprised me to see object classes inside it; there is absolutely no notion of what an entry point to this web project may be. I really could not understand the overall structure and functionality of this code.

**Comment by jpenilla** [comment]
This is not an actionable issue, if you have questions you can ask in the Discord, additionally as an open-source project you may submit PRs.
