### ISSUE TITLE
1.21.1 - Crashing at startup

### ISSUE THREAD

**Issue by emorygg** [jpenilla/squaremap#323]
Crashing on startup playing the [Craftoria](https://www.curseforge.com/minecraft/modpacks/craftoria) modpack.

Crash log: https://mclo.gs/rCQ9mBw

Minecraft - 1.21.1
Neoforge - 21.1.66
Squaremap - 1.3.2
Modpack version - 1.5

**Comment by jpenilla** [comment]
This is a bug in outdated versions of Spark
