### ISSUE TITLE
[Question] How should I update the map

### ISSUE THREAD

**Issue by ChaomengCFX** [jpenilla/squaremap#331]
I added this mod to the server **midway** and found that it caused the generated map to be very fragmented. I tried modifying the configuration file but couldn't solve the problem. What should I do to update the missing chunks, thanks
![41ea56ee-8080-42db-9b2a-cd613de1046d](https://github.com/user-attachments/assets/029e222c-c16b-474b-955b-04d2119263f0)

**Comment by tech-6** [comment]
Hey, if you haven't done a full render of your worlds yet. That should fix it for you.
`/map fullrender [world]`

**Comment by jpenilla** [comment]
As mentioned above you need to run a full render. Chunks won't render on their own unless they have block changes while squaremap is installed.
