### ISSUE TITLE
Map doesn't load, /web/tiles/settings.json doesn't exist

### ISSUE THREAD

**Issue by JonathanAlumbaugh** [jpenilla/squaremap#34]
Not sure if this is a true issue or just a user error... this error appears in the console when visiting the map, and no map appears:
![image](https://user-images.githubusercontent.com/9826603/156580564-be1813f4-98c9-4a35-b30e-9691a3473948.png)

I've confirmed the file `/web/tiles/settings.json` doesn't exist on the server, and hasn't been generated during a server restart, or a squaremap reload, or a squaremap reset.

Running git-Paper-216 (MC 1.18.1).

**Comment by jpenilla** [comment]
Confirmed to be https://bugs.openjdk.java.net/browse/JDK-8274349 via timings report on discord
