### ISSUE TITLE
Full Render Error - Moonrise Class Not Found

### ISSUE THREAD

**Issue by jtl001** [jpenilla/squaremap#353]
I'm running a Paper server (version 1.21.4), and when issuing the /squaremap fullrender command, I encounter the following error:

`
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: ca.spottedleaf.moonrise.common.util.ChunkSystem
...
Caused by: java.lang.ClassNotFoundException: ca.spottedleaf.moonrise.common.util.ChunkSystem
`

It appears that SquareMap is attempting to use the Moonrise library (ca.spottedleaf.moonrise.common.util.ChunkSystem), but I do not have Moonrise installed, as it is not stated as required, nor does it work with Paper.

Expected Behavior: SquareMap should either handle the absence of Moonrise gracefully or provide an alternative method to render the map without requiring Moonrise.

PaperMC version: 1.21.4
SquareMap version: 1.3.3 (compatible with Paper 1.21.4)

**Comment by jpenilla** [comment]
You will need to use dev builds of squaremap with Paper hard-fork builds for now https://jenkins.jpenilla.xyz/job/squaremap/

I will try and get a new release out soon

**Comment by jtl001** [comment]
Tested with latest dev build - works as expected. Thanks.
