### ISSUE TITLE
request for colored names

### ISSUE THREAD

**Issue by Elithefry** [jpenilla/squaremap#4]
would be nice to have a little customization, such as for names to be colored. 
(it's usually toggleable with true/false input on dynmap)

**Comment by jpenilla** [comment]
Colored meaning use their nickname/displayname instead of username? I'm not exactly sure what you mean.

**Comment by iElijahi** [comment]
allow me to explain :)
here's straight from the dynmap 3.0 config.txt
![image](https://user-images.githubusercontent.com/65664977/145418647-744d97e7-3c51-4904-ae2f-1a2076eb592e.png)

then if my nickname from essentialsX were (rgb/legacy codes would idealy work here), "&#084cfbG&#3176fce&#5ba0fce&#84c9fdl&#adf3fdi"

it would show up on the map like this:
![example](https://user-images.githubusercontent.com/65664977/145419128-115333d7-6814-4e85-8858-797b5bc62442.png)

**Comment by Strahilchu** [comment]
Yeah it would be nice if it could fetch player DisplayName instead of PlayerName basically
