### ISSUE TITLE
Schematics set with FAWE are not visible

### ISSUE THREAD

**Issue by arima0k** [jpenilla/squaremap#43]
I've put schematic on my server and them showed almost immediate, but with Word Edit, now with FAWE the new ones doesn't show at all.
I don't know if is just FAWE or also  Word Edit.

**Comment by jpenilla** [comment]
Not a squaremap issue.

**Comment by arima0k** [comment]
The schematics don't show on the map, but in the world, they do. I don't know if I explained it well.
