### ISSUE TITLE
Invalid command argument: No such world 

### ISSUE THREAD

**Issue by TheDarthFather** [jpenilla/squaremap#48]
Hello,
I upgraded to 1.18.2 and moved from Pl3xMap to squaremap.
I am trying to rennder my main world (MainSurvival) using:
`map fullrender MainSurvival`
But I get this error ...
`[11:40:24 INFO]: [squaremap] Invalid command argument: No such world 'MainSurvival'`
Am I missing something ?

**Comment by jpenilla** [comment]
squaremap uses world keys, not names which are a concept made up by bukkit. use tab complete to see the list of world keys

**Comment by TheDarthFather** [comment]
Thank you!

**Comment by TheDarthFather** [comment]
Thank you. 
It worked as instructed ... it finished after 2 h  the full render .... but the map is not complete as it was before 1.18.2. 
Instead there are just a few paths rendered ...
Am I doing something wrong ?

**Comment by jpenilla** [comment]
pre-1.18 chunks don't count as generated until they have been upgraded and had below 0 retrogen applied. either run chunky or fly to locations in game to upgrade them, then render again.

**Comment by TheDarthFather** [comment]
Thank you! 
... so I need to regen the chunks!

**Comment by loranger** [comment]
Hello, I had this issue, too

> squaremap uses world keys, not names which are a concept made up by bukkit. use tab complete to see the list of world keys

I use pufferpanel to manage my server(s) and the web console does not provide the tab completion.
How can I get the bukkit world key @jpenilla ?
