### ISSUE TITLE
Handle spaces in world name

### ISSUE THREAD

**Issue by nano-shino** [jpenilla/squaremap#5]
My level name has spaces in them, e.g. "World 1", and there's no way to enter it in squaremap commands.

**Examples:**
Input: `/map fullrender World 1`
Output: `Invalid command argument: No such world 'World'`

Input: `/map fullrender "World 1"`
Output: `Invalid command argument: No such world '"World'`

**Comment by jpenilla** [comment]
I don't really care to specifically support having spaces in world names, imo you should just fix your world names to not have spaces... However this is now fixed as a side effect of using keys to represent worlds like vanilla does.
