### ISSUE TITLE
server crash fabric.

### ISSUE THREAD

**Issue by netcore10** [jpenilla/squaremap#50]
[squaremapcrash.txt](https://github.com/jpenilla/squaremap/files/8748368/squaremapcrash.txt)
took me a bit to catch the error because it kept restarting the server.

**Comment by jpenilla** [comment]
Sounds like outdated squaremap, upload the full log at https://paste.gg so we can confirm the versions of everything

**Comment by netcore10** [comment]
sorry, due to me running it server side only didn't realise it updated. My bad.
