### ISSUE TITLE
World Border & GriefPrevention

### ISSUE THREAD

**Issue by TheDarthFather** [jpenilla/squaremap#51]
Hello,
I use GrifPrevention addon and ChunkyBorder.
They work great, but if i select both layouts, when I click on a claim I see the WorldBorder in the hint-popup.
Is there anyway to avoid this ?

PS: When I deselect the Worlborder layout, GP works as intended.

Thank you!

![image](https://user-images.githubusercontent.com/23462204/170704472-b497211a-25ad-4af1-a67f-4adef1edb279.png)

**Comment by jpenilla** [comment]
If your border is a circle it's probably #15, otherwise likely something with layer priority or something in the chunky border config.

**Comment by TheDarthFather** [comment]
> If your border is a circle it's probably #15, otherwise likely something with layer priority or something in the chunky border config.

Indeed - seems to be!
