### ISSUE TITLE
Strange full render on chunky

### ISSUE THREAD

**Issue by TheDarthFather** [jpenilla/squaremap#54]
Hi,
I used chunky to generate the chunks, use the border, did a trim outside.
Than did a map full render. Got this.
Did I miss something ?  

![image](https://user-images.githubusercontent.com/23462204/171052512-122ff931-d77f-4142-bd45-f6dcbe99dd2f.png)

**Comment by pop4959** [comment]
Hey, I think I can answer this for you.

First of all, you seem to have some rendered areas outside of your world border + little blips of rendered areas for example in the top right corner which are probably due to player view distance rendering past the border. Keep in mind that while trim removes these, it does not prevent these chunks from re-generating. This is usually best solved by configuring visibility limits from in the squaremap configuration.

There is a guide you can read about all of that [here](https://github.com/pop4959/Chunky/wiki/Map-rendering) for chunky + squaremap.

Once you have done all of that, you'll probably want to trim the world again, and then use the `map resetmap` and `map fullrender` command to fix your current map. You can find those commands [here](https://github.com/jpenilla/squaremap/wiki/Commands-and-Permissions) on the squaremap wiki.

If you've done all of the above your map should look neat and tidy. Good luck!

**Comment by pop4959** [comment]
> However top left is very strange ..... I dont belive visibility will help ... !? Also on right ... is not even rendered. while chunky supposed to create the chunks there .

Visibility limit should help there :)

Make sure you configure the limit as a circle that matches your border.

Pre-gen area looks odd, almost like you moved the center via config in the middle of it. I would just completely redo trim and make sure that your options are correct when you fill in the rest. That part should be fine.

> Maybe is not a map render, but a chunky issue... Not sure how chunky works, but I had chunkmaster before (deleted now) .. any chance chunky will not delete some of the chunks generated with chunkmaster !?

Probably not a chunky issue, repeating what I said above it's probably just that some options were not set correctly. You can join their Discord server if after re-trimming, re-filling, and re-rendering, it doesn't look right.

**Comment by TheDarthFather** [comment]
> > However top left is very strange ..... I dont belive visibility will help ... !? Also on right ... is not even rendered. while chunky supposed to create the chunks there .
> 
> Visibility limit should help there :)
> 
> Make sure you configure the limit as a circle that matches your border.
> 
> Pre-gen area looks odd, almost like you moved the center via config in the middle of it. I would just completely redo trim and make sure that your options are correct when you fill in the rest. That part should be fine.
> 
> > Maybe is not a map render, but a chunky issue... Not sure how chunky works, but I had chunkmaster before (deleted now) .. any chance chunky will not delete some of the chunks generated with chunkmaster !?
> 
> Probably not a chunky issue, repeating what I said above it's probably just that some options were not set correctly. You can join their Discord server if after re-trimming, re-filling, and re-rendering, it doesn't look right.

Ok, I will try. 
And indeed the map center used to be around there ... I do a 2700 2000 center now.

**Comment by jpenilla** [comment]
In general, help/support questions belong more on the discord than here, the issue tracker is for actual bugs in squaremap or feature requests.

**Comment by TheDarthFather** [comment]
> > However top left is very strange ..... I dont belive visibility will help ... !? Also on right ... is not even rendered. while chunky supposed to create the chunks there .
> 
> Visibility limit should help there :)
> 
> Make sure you configure the limit as a circle that matches your border.
> 
> Pre-gen area looks odd, almost like you moved the center via config in the middle of it. I would just completely redo trim and make sure that your options are correct when you fill in the rest. That part should be fine.
> 
> > Maybe is not a map render, but a chunky issue... Not sure how chunky works, but I had chunkmaster before (deleted now) .. any chance chunky will not delete some of the chunks generated with chunkmaster !?
> 
> Probably not a chunky issue, repeating what I said above it's probably just that some options were not set correctly. You can join their Discord server if after re-trimming, re-filling, and re-rendering, it doesn't look right.

You were right. Not a mapsquaremap-render issue. 
1. While my border was a circle .... I generated the chunks before setting it a s circle so I guess this was the main problem
2. Visibility settings work as intended!  

Thnak you again!
