### ISSUE TITLE
Modifying event-listeners in advanced.yml doesn't seem to actually change rendering.

### ISSUE THREAD

**Issue by Kaput82** [jpenilla/squaremap#63]
I've set ChunkLoadEvent to true in the advanced.yml file, and restarted my server, but as far as I can tell it isn't working.  Perhaps I'm not understanding how that is supposed to work, but I assumed as chunks are loaded they would be updated/re-rendered on the map.

If it helps I would like the map to update as players explore further out from spawn, even if they don't specifically break or lay down a block.  I also tried setting PlayerMovementEvent to true but that also didn't work they way I had hoped.  The world has been pre-generated with chunky, but I don't want to render the whole thing at once as that kind of ruins the fun of exploring.

**Comment by jpenilla** [comment]
Yes, your assumption is correct, that is how it is meant to work. Testing locally the ChunkLoadEvent trigger and it's config option both work perfectly fine, I am unable to reproduce the issue you are reporting.

The Discord linked in the readme would be a better place to get further support on this, as the issue tracker is for bug reports and feature requests.

**Comment by ZeWebDev** [comment]
This is happening to me on fabric, with crops not updating after they grow. Looking at the fabric code it seems like it doesn't take the `event-listeners` into consideration at all.
