### ISSUE TITLE
1.19.1 - players don't show on map

### ISSUE THREAD

**Issue by bdagenais2** [jpenilla/squaremap#67]
Errors in console running squaremap v1.1.7-SNAPSHOT+a2b458a on paper build #86 for 1.19.1:
https://paste.gg/p/anonymous/5c3804b3e7b74eabae751fc43c195c2d

Players do not show up on map.

**Comment by Noevenzahn** [comment]
Same issue here. Updated to 1.19.1 today, got the same warnings in the console and noticed that players don't show up on the map anymore.

**Comment by jpenilla** [comment]
You're using a 1.19 build on 1.19.1.
