### ISSUE TITLE
Server fails to start when running 1.1.8 Fabric

### ISSUE THREAD

**Issue by CarbonGhost** [jpenilla/squaremap#71]
The server fails to start when running a 1.19.2 Fabric server, here's some logs:

https://bin.bloom.host/wudeqekese

**Comment by jpenilla** [comment]
This is a [cloud issue](https://github.com/Incendo/cloud/issues/385), I'll look at fixing it in the coming days

**Comment by jpenilla** [comment]
Can you test if this is resolved in the newest dev build? https://jenkins.jpenilla.xyz/job/squaremap/lastSuccessfulBuild/

**Comment by CarbonGhost** [comment]
Sorry for the delay, this build works for me!

**Comment by jpenilla** [comment]
The fabric jar for 1.1.8 has been recompiled and re uploaded to fix this
