### ISSUE TITLE
Cannot see players on map

### ISSUE THREAD

**Issue by d0rf3n** [jpenilla/squaremap#79]
Getting spammed with this.

Found the #67, but MC is 1.19 and using latest version 1.1.8. Also tried downgrading and dev builds, same problem.

Any idea?

`[squaremap] Task #12 for squaremap v1.1.8 generated an exception
11.09 20:23:54 [Server] [INFO] java.lang.NoSuchMethodError: 'java.util.UUID net.minecraft.server.level.EntityPlayer.co()'
11.09 20:23:54 [Server] [INFO] at xyz.jpenilla.squaremap.common.AbstractPlayerManager.hidden(AbstractPlayerManager.java:71) ~[squaremap-paper-mc1.19.2-1.1.8 (2).jar:?]
11.09 20:23:54 [Server] [INFO] at xyz.jpenilla.squaremap.common.task.UpdatePlayers.lambda$run$0(UpdatePlayers.java:67) ~[squaremap-paper-mc1.19.2-1.1.8 (2).jar:?]
11.09 20:23:54 [Server] [INFO] at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
11.09 20:23:54 [Server] [INFO] at xyz.jpenilla.squaremap.common.task.UpdatePlayers.lambda$run$1(UpdatePlayers.java:60) ~[squaremap-paper-mc1.19.2-1.1.8 (2).jar:?]
11.09 20:23:54 [Server] [INFO] at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
11.09 20:23:54 [Server] [INFO] at xyz.jpenilla.squaremap.common.task.UpdatePlayers.run(UpdatePlayers.java:57) ~[squaremap-paper-mc1.19.2-1.1.8 (2).jar:?]
11.09 20:23:54 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-"86f87ba"]
11.09 20:23:54 [Server] [INFO] at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-"86f87ba"]
11.09 20:23:54 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1491) ~[paper-1.19.jar:git-Paper-"86f87ba"]
11.09 20:23:54 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-"86f87ba"]
11.09 20:23:54 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-"86f87ba"]
11.09 20:23:54 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-"86f87ba"]
11.09 20:23:54 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-"86f87ba"]
11.09 20:23:54 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) ~[?:?]`

**Comment by jpenilla** [comment]
You're using a plugin for 1.19.2 on 1.19. You can use the old unsupported squaremap builds, but I would recommend updating your server instead.
