### ISSUE TITLE
The webmap just says took too long to respond

### ISSUE THREAD

**Issue by normaluser12354** [jpenilla/squaremap#85]
When trying to make the map viewable online, it says took too long to respond
also using the IP:port method and using self-hosting.

**Comment by jpenilla** [comment]
This sounds like you haven't forwarded the port used by the internal web server. Without doing that `IP:port` will only work using local IPs over LAN.

**Comment by normaluser12354** [comment]
i think i found out how to do the ip now
by using the network ip
