### ISSUE TITLE
Chunks that were generated before adding squaremap are not loading

### ISSUE THREAD

**Issue by Spider987** [jpenilla/squaremap#88]
Chunks that were generated before I added square map to my server are not appearing on the map. Newly generated chunks are. I have tried going into advanced config to make it so the map updates on chunkload, but the option isn't even there.

**Comment by wesleezz** [comment]
same problem

**Comment by jpenilla** [comment]
Use the `/map fullrender` or `/map radiusrender` commands, keep in mind you may need to run chunky/load the chunks in game first if they haven't been upgraded for the new world height yet. If you need more help the discord linked in the readme would be the best place to ask.
