### ISSUE TITLE
`Bug` Failed to write file '.\squaremap\web\tiles\players.json' + Timed out waiting for world statistics

### ISSUE THREAD

**Issue by zndrmn** [jpenilla/squaremap#96]
Was just working on my build and all of a sudden the server started to lag like crazy, it then timed me out and I went to the console and ran the /help command, which took a few mins for it to respond. It later fixed itself, not sure why any of this happened.

server log: [2023-03-31-1.log](https://gist.github.com/zndrmn/33acd2961ab0c081ef709d588fa52d58#file-2023-03-31-1-log)

**Comment by jpenilla** [comment]
Your server is lagging, but there's nothing here to tell us what's causing it, you would need to take a spark report while the lag is happening to debug it further. Spark timing out and squaremap having issues writing files are symptoms of this lag. Also, only the latest release of squaremap is supported.

**Comment by zndrmn** [comment]
strange, If this ever happens again I'll try and create a spark report and create a new issue. Though I'm sure this probably won't happen again.
