### ISSUE TITLE
[BUG] crash upon running radiusrender from console

### ISSUE THREAD

**Issue by lerokko** [jpenilla/squaremap#98]
I tried running `/map radiusrender minecraft:overworld 2000 10000 300` as a vanished player in spectator and got no feedback on the command. I had the right permissions and was unsure if it would start since I am vanished so I though "Can't hurt to run that command a second time from console to be sure."
Nope. As soon as I ran it from console it crashed. I am not sure if the issue is solely on squaremap or has to do with other plugins or something else but I wanted to provide the crash-log here regardless.

crash report: https://mclo.gs/7WRuwDi

**Comment by jpenilla** [comment]
Sadly a crash report isn't really useful here, need the server log to say anything.

**Comment by lerokko** [comment]
Here is the begging and end of the log from that day.
It seems that DiscordSRV was the culprit and not squaremap.
https://mclo.gs/pjZyLYs#L559

**Comment by jpenilla** [comment]
> Here is the begging and end of the log from that day. It seems that DiscordSRV was the culprit and not squaremap. [mclo.gs/pjZyLYs#L559](https://mclo.gs/pjZyLYs#L559)

Thanks for the update, going to close this now then
